version: '3.8'

services:
  backend:
    image: temp-octafood-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    image: temp-octafood-frontend:latest
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
